### ISSUE TITLE
OMG Network lacking moderated developer forum.

### ISSUE THREAD

**Issue by snowkidind** [omgnetwork/omgnetwork.github.io#109]
Hi there are times when the documentation is not enough and some sort of informal communication is necessary to complete an integration. Consider my current pondering: 

_I have two addresses and two keys - wallet A and wallet B - one containing eth, the other containing erc20. Is it possible to pay to send the erc20 from wallet B with the eth for gas from Wallet A to third party (wallet c) in a single transaction._

I cannot answer this question with the current docs, and if yes or no, the answer would be useful to future developers. I remember gitter.im was useful for something like this but that location looks dead for at least a year. 

My suggestion is to have a user forum linked directly on this site. 

Could use something like Redmine (RoR) and also have it serve as a front facing bug reporting tool for non-githubbers. Even UltimateBB (PHP) would be an improvement on nothing.

**Comment by dmitrydao** [comment]
Hey. Thanks for reaching out. We currently don't run such a forum but you can always ask questions in the intercom chat on the dev portal. Somebody always picks it up.

With regard to your question specifically, it can be done. You need to create a transaction with 2 inputs: one input from account A spending OMG for the fee and the other input from account B spending the erc20 token. Each account needs to sign the transaction. We currently don't have the code sample on the dev portal but you can check out the code used to create [fee-relayer](https://github.com/omgnetwork/community-points/tree/master/fee-relayer/src) transactions for the Community Points engine. 

Let me know if that helps.

**Comment by snowkidind** [comment]
Thanks, it was the answer I was hoping for. Eventually I will know all the nuts and bolts, but I can imagine mad scientists looking to build on Layer 2 will be looking for things of this nature often.

**Comment by dmitrydao** [comment]
Just realised I haven't sent you the link to the new code sample we released recently. It fully covers your issue:
https://docs.omg.network/network/fee-relay
