### ISSUE TITLE
Small typos on Atomic Swap Page

### ISSUE THREAD

**Issue by efulton985** [omgnetwork/omgnetwork.github.io#118]
https://docs.omg.network/network/atomic-swap#utxo-change-helper
`transactionBody.outputs.lenght` should be `length`

https://docs.omg.network/network/atomic-swap#utxo-helper
`${amount}` should be `${spendAmount}`

**Comment by dmitrydao** [comment]
Nice one. Thanks for catching. Will fix soon.

**Comment by dmitrydao** [comment]
Fixed with the last PR
